UPDATE SUPERSTORE_CLEAN
SET 
   "CUSTOMER_NAME" = TRIM("CUSTOMER_NAME"),
   "PRODUCT_NAME"  = TRIM("PRODUCT_NAME"),
   "CITY"          = TRIM("CITY"),
   "STATE"         = TRIM("STATE");
   
UPDATE SUPERSTORE_CLEAN
SET "CATEGORY" = upper("CATEGORY");   

DELETE FROM SUPERSTORE_CLEAN
WHERE SALES <= 0;


UPDATE SUPERSTORE_CLEAN
SET PROFIT_MARGIN = ROUND((PROFIT / SALES)*100, 2);
